List<Map<String, dynamic>> kategori = [
  {
    "Nama Event": "Ngopi Guys",
    "Lokasi Event": "Warkop DKI",
    "ID": "10000001",
    "Jumlah Peserta": 2,
  },
  {
    "Nama Event": "Flutter Study Jam",
    "Lokasi Event": "PPKD Jakarta Pusat",
    "ID": "10000002",
    "Jumlah Peserta": 25,
  },
  {
    "Nama Event": "Seminar Teknologi AI",
    "Lokasi Event": "Aula Universitas Indonesia",
    "ID": "10000003",
    "Jumlah Peserta": 120,
  },
  {
    "Nama Event": "Workshop UI/UX Figma",
    "Lokasi Event": "Co-Working Space Sudirman",
    "ID": "10000004",
    "Jumlah Peserta": 40,
  },
  {
    "Nama Event": "Komunitas Startup Meetup",
    "Lokasi Event": "Jakarta Creative Hub",
    "ID": "10000005",
    "Jumlah Peserta": 75,
  },
  {
    "Nama Event": "Pelatihan Mobile Developer",
    "Lokasi Event": "Gedung Kominfo",
    "ID": "10000006",
    "Jumlah Peserta": 60,
  },
  {
    "Nama Event": "Hackathon 24 Jam",
    "Lokasi Event": "Tech Park BSD",
    "ID": "10000007",
    "Jumlah Peserta": 150,
  },
  {
    "Nama Event": "Networking Night",
    "Lokasi Event": "Hotel Grand Mercure",
    "ID": "10000008",
    "Jumlah Peserta": 90,
  },
  {
    "Nama Event": "Bootcamp App Developer",
    "Lokasi Event": "PPKD Jakarta Pusat",
    "ID": "10000009",
    "Jumlah Peserta": 30,
  },
  {
    "Nama Event": "Diskusi Produk Digital",
    "Lokasi Event": "Perpustakaan Nasional",
    "ID": "10000010",
    "Jumlah Peserta": 55,
  },
  {
    "Nama Event": "Kelas Dart Fundamental",
    "Lokasi Event": "Ruang 3A PPKD",
    "ID": "10000011",
    "Jumlah Peserta": 20,
  },
  {
    "Nama Event": "Seminar Cyber Security",
    "Lokasi Event": "Balai Kota Jakarta",
    "ID": "10000012",
    "Jumlah Peserta": 110,
  },
  {
    "Nama Event": "Workshop Firebase",
    "Lokasi Event": "Google Space Jakarta",
    "ID": "10000013",
    "Jumlah Peserta": 45,
  },
  {
    "Nama Event": "Tech Career Expo",
    "Lokasi Event": "JIExpo Kemayoran",
    "ID": "10000014",
    "Jumlah Peserta": 300,
  },
  {
    "Nama Event": "Community Sharing Session",
    "Lokasi Event": "Cafe Kopi Kenangan",
    "ID": "10000015",
    "Jumlah Peserta": 18,
  },
  {
    "Nama Event": "Digital Marketing Talk",
    "Lokasi Event": "Hotel Pullman",
    "ID": "10000016",
    "Jumlah Peserta": 85,
  },
  {
    "Nama Event": "Startup Pitching Day",
    "Lokasi Event": "WeWork Indonesia",
    "ID": "10000017",
    "Jumlah Peserta": 65,
  },
  {
    "Nama Event": "Belajar Git & GitHub",
    "Lokasi Event": "Lab Komputer PPKD",
    "ID": "10000018",
    "Jumlah Peserta": 35,
  },
  {
    "Nama Event": "Design Thinking Class",
    "Lokasi Event": "BINUS University",
    "ID": "10000019",
    "Jumlah Peserta": 70,
  },
  {
    "Nama Event": "AI for Beginner",
    "Lokasi Event": "Universitas Negeri Jakarta",
    "ID": "10000020",
    "Jumlah Peserta": 95,
  },
];
